name: helpy_ninja
description: "AI-powered tutoring platform with personalized multi-agent learning"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: 
  riverpod_annotation: 
  # Navigation
  go_router: 

  # Network & API
  dio: 
  web_socket_channel: 
  connectivity_plus:

  # Local Storage
  hive: 
  hive_flutter: 
  shared_preferences: 

  # UI Components
  flutter_math_fork: 
  flutter_svg: 
  cached_network_image: 
  shimmer: 
  google_fonts: 
  syncfusion_flutter_charts: 
  # Platform Features
  speech_to_text:
  flutter_tts: 
  camera: 
  image_picker: 

  # Localization
  intl: 

  # Utilities
  uuid:
  logger:
  equatable: 
  freezed_annotation: 
  json_annotation:

  # Dependency Injection
  get_it:
  injectable:

  # Security
  flutter_secure_storage:

  # Local ML (for offline LLM)
  tflite_flutter: 

  # Icons
  cupertino_icons: 
  path:
  path_provider: 
  markdown: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  riverpod_generator: 
  build_runner:
  hive_generator: 
  json_serializable: 
  freezed:
  injectable_generator: 

  # Localization
  intl_utils: 

  # Testing
  mockito: 
  mocktail: 

  # Analysis
  flutter_lints: 
  very_good_analysis: 

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/models/
