name: helpy_ninja
description: "AI-powered tutoring platform with personalized multi-agent learning"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.0

  # Navigation
  go_router: ^12.0.0

  # Network & API
  dio: ^5.3.2
  web_socket_channel: ^2.4.0
  connectivity_plus: ^5.0.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # UI Components
  flutter_markdown: ^0.6.18
  flutter_math_fork: ^0.7.1
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  google_fonts: ^6.1.0

  # Platform Features
  speech_to_text: ^6.3.0
  flutter_tts: ^3.8.3
  camera: ^0.10.5+5
  image_picker: ^1.0.4

  # Localization
  intl: ^0.20.2

  # Utilities
  uuid: ^4.1.0
  logger: ^2.0.2+1
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Local ML (for offline LLM)
  tflite_flutter: ^0.10.4

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  riverpod_generator: ^2.3.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  freezed: ^2.4.6

  # Localization
  intl_utils: ^2.8.5

  # Testing
  mockito: ^5.4.2
  mocktail: ^1.0.1

  # Analysis
  flutter_lints: ^3.0.0
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/models/
